import 'package:flutter/material.dart';

const Color primaryColor = Color(0xFF001834);
const Color whiteColor = Color(0xFFFFFFFF);
const Color backgroundColor = Color(0xFFEAEDED);
const Color mapColor = Color(0xFF002D62);
const Color blueColor = Color(0xFF0038FF);
const Color blackColor = Color(0xFF000000);
const Color buttonColor = Color(0xFF0F2E71);
const Color greyColor = Colors.grey;
const Color greenColor = Color(0xFF128200);
const Color lightblue = Color(0xFFF2F6FF);
const Color redColor = Colors.red;
const Color greyLightColor = Color(0xFFF3F4F6);
const Color lightBackGroundColor = Color(0xFFF3F4F6);
const Color yellowColor = Colors.yellow;
const Color lightGreenColor = Color.fromARGB(255, 148, 236, 150);
const Color orangeColor = Color(0xFFFFA438);
const Color lightblueColor = Color(0xFFF2F6FF);
const Color GetlightblueColor = Color.fromRGBO(75, 110, 232, 1);
const Color GetLightGreyColor = Color.fromRGBO(196, 196, 196, 1);
const Color GetDarkBlueColor =Color.fromRGBO(15, 46, 113, 1);
